#!/usr/bin/env bash
# Llama Manager — safe configuration editor for local development and operations.
# Copyright (c) Llama Manager project. Use of this file is governed by the
# LICENSE file in the repository root.
#
# Safely edits .env files, typed JSON configuration, orchestrator settings, and
# project tokens while masking credential-like values in every displayed result.
#
# Usage:
#   ./scripts/dev-config.sh env set KEY VALUE       # Set a .env variable
#   ./scripts/dev-config.sh env get KEY             # Get a .env variable (masked if sensitive)
#   ./scripts/dev-config.sh env list                # List all .env variables (sensitive values masked)
#   ./scripts/dev-config.sh env delete KEY          # Remove a .env variable
#
#   ./scripts/dev-config.sh file set FILE KEY VALUE # Set a value in a config file (.env or .json)
#   ./scripts/dev-config.sh file get FILE KEY       # Get a value from a config file (masked if sensitive)
#   ./scripts/dev-config.sh file list FILE          # List all values in a config file (sensitive masked)
#   ./scripts/dev-config.sh file delete FILE KEY    # Remove a key from a config file
#   ./scripts/dev-config.sh file formats            # List supported file formats
#
#   ./scripts/dev-config.sh setting set KEY VALUE   # Set an orchestrator setting (via API)
#   ./scripts/dev-config.sh setting get KEY         # Get an orchestrator setting
#   ./scripts/dev-config.sh setting list            # List all orchestrator settings
#
#   ./scripts/dev-config.sh project set-token ID TOKEN   # Set GitHub token on a project
#   ./scripts/dev-config.sh project list                 # List projects (token status)
#
# Sensitive keys (masked in output):
#   *TOKEN*, *SECRET*, *KEY*, *PASSWORD*, *CREDENTIAL*, *API_KEY*, *APIKEY*

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

ENV_FILE="${ROOT_DIR}/.env"

# Source PORT from .env if not already set
_port="${PORT:-}"
if [ -z "$_port" ] && [ -f "$ENV_FILE" ]; then
  _port="$(grep -m1 '^PORT=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- || echo "3000")"
fi
API_URL="${ORCHESTRATOR_URL:-http://localhost:${_port:-3000}}"

# Patterns that indicate sensitive values (case-insensitive match)
SENSITIVE_PATTERNS="TOKEN|SECRET|KEY|PASSWORD|CREDENTIAL|API_KEY|APIKEY"

is_sensitive() {
  local key="$1"
  echo "$key" | grep -qiE "$SENSITIVE_PATTERNS"
}

mask_value() {
  local val="$1"
  if [ ${#val} -le 4 ]; then
    echo "****"
  else
    echo "${val:0:4}...$(echo "$val" | wc -c | tr -d ' ')chars"
  fi
}

# ---------------------------------------------------------------------------
# .env management
# ---------------------------------------------------------------------------

env_set() {
  local key="$1" value="$2"

  if [ ! -f "$ENV_FILE" ]; then
    echo "# Generated by dev-config.sh" > "$ENV_FILE"
  fi

  # Check if key already exists
  if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    # Replace existing value (use node to avoid sed issues on Windows)
    node -e "
      const fs=require('fs');
      const file=process.argv[1], key=process.argv[2], val=process.argv[3];
      let content=fs.readFileSync(file,'utf8');
      const re=new RegExp('^'+key.replace(/[.*+?^\${}()|[\\]\\\\]/g,'\\\\$$&')+'=.*$$','m');
      content=content.replace(re, key+'='+val);
      fs.writeFileSync(file,content);
    " "$ENV_FILE" "$key" "$value"
    echo "Updated: ${key}"
  else
    # Append new key
    echo "${key}=${value}" >> "$ENV_FILE"
    echo "Added: ${key}"
  fi

  if is_sensitive "$key"; then
    echo "Value: $(mask_value "$value")"
  else
    echo "Value: ${value}"
  fi
}

env_get() {
  local key="$1"

  if [ ! -f "$ENV_FILE" ]; then
    echo "No .env file found"
    return 1
  fi

  local line
  line=$(grep "^${key}=" "$ENV_FILE" 2>/dev/null || true)
  if [ -z "$line" ]; then
    echo "${key}: (not set)"
    return 1
  fi

  local value="${line#*=}"
  if is_sensitive "$key"; then
    echo "${key}=$(mask_value "$value")"
  else
    echo "${key}=${value}"
  fi
}

env_list() {
  if [ ! -f "$ENV_FILE" ]; then
    echo "No .env file found"
    return 1
  fi

  echo "=== ${ENV_FILE} ==="
  while IFS= read -r line; do
    # Skip comments and empty lines
    [[ "$line" =~ ^[[:space:]]*# ]] && { echo "$line"; continue; }
    [[ -z "$line" ]] && { echo; continue; }

    local key="${line%%=*}"
    local value="${line#*=}"

    if is_sensitive "$key"; then
      echo "${key}=$(mask_value "$value")"
    else
      echo "$line"
    fi
  done < "$ENV_FILE"
}

env_delete() {
  local key="$1"

  if [ ! -f "$ENV_FILE" ]; then
    echo "No .env file found"
    return 1
  fi

  if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    node -e "
      const fs=require('fs');
      const file=process.argv[1], key=process.argv[2];
      let content=fs.readFileSync(file,'utf8');
      const re=new RegExp('^'+key.replace(/[.*+?^\${}()|[\\]\\\\]/g,'\\\\$$&')+'=.*\\n?','m');
      content=content.replace(re, '');
      fs.writeFileSync(file,content);
    " "$ENV_FILE" "$key"
    echo "Deleted: ${key}"
  else
    echo "${key} not found in .env"
  fi
}

# ---------------------------------------------------------------------------
# Orchestrator settings (via API)
# ---------------------------------------------------------------------------

setting_set() {
  local key="$1" value="$2"

  if ! curl -sf "${API_URL}/api/v1/settings/setup/status" >/dev/null 2>&1; then
    echo "ERROR: API not responding at ${API_URL}"
    echo "Start with: ./scripts/dev-server.sh start"
    return 1
  fi

  local result
  result=$(curl -sf "${API_URL}/api/v1/settings" -X PUT \
    -H "Content-Type: application/json" \
    -d "{\"key\":\"${key}\",\"value\":\"${value}\"}" 2>/dev/null)

  if echo "$result" | node -e "const d=[];process.stdin.on('data',c=>d.push(c));process.stdin.on('end',()=>{process.exit(JSON.parse(d.join('')).success?0:1)})" 2>/dev/null; then
    echo "Setting updated: ${key}"
    if is_sensitive "$key"; then
      echo "Value: $(mask_value "$value")"
    else
      echo "Value: ${value}"
    fi
  else
    echo "FAILED to update setting: ${key}"
    echo "Response: ${result}"
  fi
}

setting_get() {
  local key="$1"

  if ! curl -sf "${API_URL}/api/v1/settings/setup/status" >/dev/null 2>&1; then
    echo "ERROR: API not responding at ${API_URL}"
    return 1
  fi

  curl -sf "${API_URL}/api/v1/settings" | node -e "
    const d=[];process.stdin.on('data',c=>d.push(c));
    process.stdin.on('end',()=>{
      const settings=JSON.parse(d.join('')).data;
      const key='${key}';
      const s=settings.find(s=>s.key===key);
      if(!s){console.log(key+': (not found)');process.exit(1)}
      const val=s.value||'(empty)';
      if(s.sensitive&&s.value){
        console.log(s.key+'='+val.substring(0,4)+'...'+val.length+'chars');
      } else {
        console.log(s.key+'='+val);
      }
      if(s.description) console.log('  '+s.description);
    })" 2>/dev/null
}

setting_list() {
  if ! curl -sf "${API_URL}/api/v1/settings/setup/status" >/dev/null 2>&1; then
    echo "ERROR: API not responding at ${API_URL}"
    return 1
  fi

  curl -sf "${API_URL}/api/v1/settings" | node -e "
    const d=[];process.stdin.on('data',c=>d.push(c));
    process.stdin.on('end',()=>{
      const settings=JSON.parse(d.join('')).data;
      console.log('Key'.padEnd(40),'Value'.padEnd(30),'Category');
      console.log('-'.repeat(80));
      settings.forEach(s=>{
        let val=s.value||'(empty)';
        if(s.sensitive&&s.value) val=val.substring(0,4)+'...';
        console.log(s.key.padEnd(40),val.substring(0,29).padEnd(30),s.category||'');
      });
    })" 2>/dev/null
}

# ---------------------------------------------------------------------------
# Project token management
# ---------------------------------------------------------------------------

project_set_token() {
  local project_id="$1" token="$2"

  if ! curl -sf "${API_URL}/api/v1/settings/setup/status" >/dev/null 2>&1; then
    echo "ERROR: API not responding at ${API_URL}"
    return 1
  fi

  local result
  result=$(curl -sf "${API_URL}/api/v1/projects/${project_id}" -X PATCH \
    -H "Content-Type: application/json" \
    -d "{\"githubToken\":\"${token}\"}" 2>/dev/null)

  if echo "$result" | node -e "const d=[];process.stdin.on('data',c=>d.push(c));process.stdin.on('end',()=>{process.exit(JSON.parse(d.join('')).success?0:1)})" 2>/dev/null; then
    echo "GitHub token set for project ${project_id}"
    echo "Token: $(mask_value "$token")"
  else
    echo "FAILED to set token. Response: ${result}"
  fi
}

project_list() {
  if ! curl -sf "${API_URL}/api/v1/settings/setup/status" >/dev/null 2>&1; then
    echo "ERROR: API not responding at ${API_URL}"
    return 1
  fi

  curl -sf "${API_URL}/api/v1/projects" | node -e "
    const d=[];process.stdin.on('data',c=>d.push(c));
    process.stdin.on('end',()=>{
      const projects=JSON.parse(d.join('')).data;
      console.log('ID'.padEnd(26),'Name'.padEnd(25),'Repo'.padEnd(45),'GH Token');
      console.log('-'.repeat(105));
      projects.forEach(p=>{
        const token=p.githubToken?(p.githubToken.substring(0,4)+'...'):'(unset)';
        console.log(
          p.id.padEnd(26),
          (p.name||'').substring(0,24).padEnd(25),
          (p.repositoryUrl||'').substring(0,44).padEnd(45),
          token
        );
      });
    })" 2>/dev/null
}

# ---------------------------------------------------------------------------
# Generic file management (supports .env and .json)
# ---------------------------------------------------------------------------

SUPPORTED_FORMATS=".env .json"

detect_format() {
  local filepath="$1"
  local ext="${filepath##*.}"

  case "$ext" in
    json) echo "json" ;;
    env)  echo "env" ;;
    *)
      # Check if it looks like a .env file (no extension but KEY=VALUE format)
      if [ -f "$filepath" ]; then
        # Check first non-empty, non-comment line
        local first_line
        first_line=$(grep -v '^\s*#' "$filepath" 2>/dev/null | grep -v '^\s*$' | head -1 || true)
        if echo "$first_line" | grep -qE '^[A-Za-z_][A-Za-z0-9_]*='; then
          echo "env"
          return
        fi
        # Try parsing as JSON
        if node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$filepath" 2>/dev/null; then
          echo "json"
          return
        fi
      fi
      echo "unknown"
      ;;
  esac
}

file_check_format() {
  local filepath="$1"
  if [ ! -f "$filepath" ]; then
    echo "ERROR: File not found: ${filepath}"
    return 1
  fi

  local fmt
  fmt=$(detect_format "$filepath")
  if [ "$fmt" = "unknown" ]; then
    echo "ERROR: Unsupported file format for: ${filepath}"
    echo "Supported formats: ${SUPPORTED_FORMATS}"
    echo "Files must be .json or .env (KEY=VALUE) format."
    return 1
  fi
  echo "$fmt"
}

file_set() {
  local filepath="$1" key="$2" value="$3"

  # Create file if it doesn't exist — detect format from extension
  if [ ! -f "$filepath" ]; then
    local ext="${filepath##*.}"
    case "$ext" in
      json) echo "{}" > "$filepath" ;;
      env|*) echo "# Generated by dev-config.sh" > "$filepath" ;;
    esac
  fi

  local fmt
  fmt=$(file_check_format "$filepath") || return 1

  case "$fmt" in
    json)
      node -e "
        const fs=require('fs');
        const file=process.argv[1], key=process.argv[2], input=process.argv[3];
        let val;
        try { val=JSON.parse(input); } catch { val=input; }
        let obj=JSON.parse(fs.readFileSync(file,'utf8'));
        // Support dotted keys (e.g., 'auth.github.clientId')
        const parts=key.split('.');
        let target=obj;
        for(let i=0;i<parts.length-1;i++){
          if(!target[parts[i]]||typeof target[parts[i]]!=='object') target[parts[i]]={};
          target=target[parts[i]];
        }
        target[parts[parts.length-1]]=val;
        fs.writeFileSync(file,JSON.stringify(obj,null,2)+'\n');
      " "$filepath" "$key" "$value"
      ;;
    env)
      if grep -q "^${key}=" "$filepath" 2>/dev/null; then
        node -e "
          const fs=require('fs');
          const file=process.argv[1], key=process.argv[2], val=process.argv[3];
          let content=fs.readFileSync(file,'utf8');
          const re=new RegExp('^'+key.replace(/[.*+?^\${}()|[\\\\]\\\\\\\\]/g,'\\\\\\\\\\$&')+'=.*$','m');
          content=content.replace(re, key+'='+val);
          fs.writeFileSync(file,content);
        " "$filepath" "$key" "$value"
      else
        echo "${key}=${value}" >> "$filepath"
      fi
      ;;
  esac

  echo "Updated ${filepath} [${fmt}]: ${key}"
  if is_sensitive "$key"; then
    echo "Value: $(mask_value "$value")"
  else
    echo "Value: ${value}"
  fi
}

file_get() {
  local filepath="$1" key="$2"
  local fmt
  fmt=$(file_check_format "$filepath") || return 1

  case "$fmt" in
    json)
      node -e "
        const fs=require('fs');
        const file=process.argv[1], key=process.argv[2];
        const sensitive=/TOKEN|SECRET|KEY|PASSWORD|CREDENTIAL|API_KEY|APIKEY/i;
        let obj=JSON.parse(fs.readFileSync(file,'utf8'));
        const parts=key.split('.');
        let val=obj;
        for(const p of parts){
          if(val==null||typeof val!=='object'){val=undefined;break}
          val=val[p];
        }
        if(val===undefined){console.log(key+': (not found)');process.exit(1)}
        const strVal=typeof val==='object'?JSON.stringify(val):String(val);
        if(sensitive.test(key)){
          const masked=strVal.length<=4?'****':strVal.substring(0,4)+'...'+strVal.length+'chars';
          console.log(key+'='+masked);
        } else {
          console.log(key+'='+strVal);
        }
      " "$filepath" "$key"
      ;;
    env)
      local line
      line=$(grep "^${key}=" "$filepath" 2>/dev/null || true)
      if [ -z "$line" ]; then
        echo "${key}: (not found)"
        return 1
      fi
      local value="${line#*=}"
      if is_sensitive "$key"; then
        echo "${key}=$(mask_value "$value")"
      else
        echo "${key}=${value}"
      fi
      ;;
  esac
}

file_list() {
  local filepath="$1"
  local fmt
  fmt=$(file_check_format "$filepath") || return 1

  echo "=== ${filepath} [${fmt}] ==="

  case "$fmt" in
    json)
      node -e "
        const fs=require('fs');
        const sensitive=/TOKEN|SECRET|KEY|PASSWORD|CREDENTIAL|API_KEY|APIKEY/i;
        const obj=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));
        function walk(o, prefix){
          for(const[k,v] of Object.entries(o)){
            const fullKey=prefix?prefix+'.'+k:k;
            if(v&&typeof v==='object'&&!Array.isArray(v)){
              walk(v,fullKey);
            } else {
              const strVal=typeof v==='object'?JSON.stringify(v):String(v);
              if(sensitive.test(fullKey)){
                const masked=strVal.length<=4?'****':strVal.substring(0,4)+'...'+strVal.length+'chars';
                console.log(fullKey+'='+masked);
              } else {
                console.log(fullKey+'='+strVal);
              }
            }
          }
        }
        walk(obj,'');
      " "$filepath"
      ;;
    env)
      while IFS= read -r line; do
        [[ "$line" =~ ^[[:space:]]*# ]] && { echo "$line"; continue; }
        [[ -z "$line" ]] && { echo; continue; }
        local key="${line%%=*}"
        local value="${line#*=}"
        if is_sensitive "$key"; then
          echo "${key}=$(mask_value "$value")"
        else
          echo "$line"
        fi
      done < "$filepath"
      ;;
  esac
}

file_delete() {
  local filepath="$1" key="$2"
  local fmt
  fmt=$(file_check_format "$filepath") || return 1

  case "$fmt" in
    json)
      node -e "
        const fs=require('fs');
        const file=process.argv[1], key=process.argv[2];
        let obj=JSON.parse(fs.readFileSync(file,'utf8'));
        const parts=key.split('.');
        let target=obj;
        for(let i=0;i<parts.length-1;i++){
          if(!target[parts[i]]||typeof target[parts[i]]!=='object'){
            console.log(key+' not found');process.exit(1);
          }
          target=target[parts[i]];
        }
        if(!(parts[parts.length-1] in target)){
          console.log(key+' not found');process.exit(1);
        }
        delete target[parts[parts.length-1]];
        fs.writeFileSync(file,JSON.stringify(obj,null,2)+'\n');
        console.log('Deleted: '+key);
      " "$filepath" "$key"
      ;;
    env)
      if grep -q "^${key}=" "$filepath" 2>/dev/null; then
        node -e "
          const fs=require('fs');
          const file=process.argv[1], key=process.argv[2];
          let content=fs.readFileSync(file,'utf8');
          const re=new RegExp('^'+key.replace(/[.*+?^\${}()|[\\\\]\\\\\\\\]/g,'\\\\\\\\\\$&')+'=.*\\\\n?','m');
          content=content.replace(re, '');
          fs.writeFileSync(file,content);
        " "$filepath" "$key"
        echo "Deleted: ${key}"
      else
        echo "${key} not found in ${filepath}"
      fi
      ;;
  esac
}

file_formats() {
  echo "Supported config file formats:"
  echo ""
  echo "  .env     KEY=VALUE format (also files without extension that match this pattern)"
  echo "           Example: ANTHROPIC_API_KEY=sk-ant-..."
  echo ""
  echo "  .json    JSON object format (supports dotted key paths)"
  echo "           Example key: auth.github.clientId"
  echo ""
  echo "Sensitive key patterns (values are masked in all output):"
  echo "  TOKEN, SECRET, KEY, PASSWORD, CREDENTIAL, API_KEY, APIKEY"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
case "${1:-help}" in
  env)
    case "${2:-help}" in
      set)    [ -z "${3:-}" ] || [ -z "${4:-}" ] && { echo "Usage: $0 env set KEY VALUE"; exit 1; }; env_set "$3" "$4" ;;
      get)    [ -z "${3:-}" ] && { echo "Usage: $0 env get KEY"; exit 1; }; env_get "$3" ;;
      list)   env_list ;;
      delete) [ -z "${3:-}" ] && { echo "Usage: $0 env delete KEY"; exit 1; }; env_delete "$3" ;;
      *)      echo "Usage: $0 env {set KEY VALUE|get KEY|list|delete KEY}" ;;
    esac
    ;;
  file)
    case "${2:-help}" in
      set)     [ -z "${3:-}" ] || [ -z "${4:-}" ] || [ -z "${5:-}" ] && { echo "Usage: $0 file set FILE KEY VALUE"; exit 1; }; file_set "$3" "$4" "$5" ;;
      get)     [ -z "${3:-}" ] || [ -z "${4:-}" ] && { echo "Usage: $0 file get FILE KEY"; exit 1; }; file_get "$3" "$4" ;;
      list)    [ -z "${3:-}" ] && { echo "Usage: $0 file list FILE"; exit 1; }; file_list "$3" ;;
      delete)  [ -z "${3:-}" ] || [ -z "${4:-}" ] && { echo "Usage: $0 file delete FILE KEY"; exit 1; }; file_delete "$3" "$4" ;;
      formats) file_formats ;;
      *)       echo "Usage: $0 file {set FILE KEY VALUE|get FILE KEY|list FILE|delete FILE KEY|formats}" ;;
    esac
    ;;
  setting)
    case "${2:-help}" in
      set)    [ -z "${3:-}" ] || [ -z "${4:-}" ] && { echo "Usage: $0 setting set KEY VALUE"; exit 1; }; setting_set "$3" "$4" ;;
      get)    [ -z "${3:-}" ] && { echo "Usage: $0 setting get KEY"; exit 1; }; setting_get "$3" ;;
      list)   setting_list ;;
      *)      echo "Usage: $0 setting {set KEY VALUE|get KEY|list}" ;;
    esac
    ;;
  project)
    case "${2:-help}" in
      set-token) [ -z "${3:-}" ] || [ -z "${4:-}" ] && { echo "Usage: $0 project set-token PROJECT_ID TOKEN"; exit 1; }; project_set_token "$3" "$4" ;;
      list)      project_list ;;
      *)         echo "Usage: $0 project {set-token PROJECT_ID TOKEN|list}" ;;
    esac
    ;;
  *)
    echo "Usage: $0 <scope> <command> [args...]"
    echo ""
    echo "Scopes:"
    echo "  env        Manage the root .env file"
    echo "    set KEY VALUE       Set/update a variable"
    echo "    get KEY             Get a variable (sensitive values masked)"
    echo "    list                List all variables"
    echo "    delete KEY          Remove a variable"
    echo ""
    echo "  file       Manage any config file (.env or .json format)"
    echo "    set FILE KEY VALUE  Set a value in a config file"
    echo "    get FILE KEY        Get a value (sensitive values masked)"
    echo "    list FILE           List all values (sensitive values masked)"
    echo "    delete FILE KEY     Remove a key"
    echo "    formats             List supported file formats"
    echo ""
    echo "  setting    Manage orchestrator settings (via API)"
    echo "    set KEY VALUE       Set a setting"
    echo "    get KEY             Get a setting"
    echo "    list                List all settings"
    echo ""
    echo "  project    Manage project configuration"
    echo "    set-token ID TOKEN  Set GitHub token on a project"
    echo "    list                List projects with token status"
    echo ""
    echo "Sensitive values (matching TOKEN, SECRET, KEY, PASSWORD, CREDENTIAL, API_KEY, APIKEY)"
    echo "are automatically masked in output to prevent accidental exposure."
    exit 1
    ;;
esac
